POST http://localhost:8080/vehicles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAiLCJleHAiOjE3MzU2NDYwNzUsInVzZXJJZCI6IjY1OTJhNzRjYTg0NjM3MDgxODhjNmEwMSJ9.5R4sPftZNT1PcjN8xLQ4FIQJGzimSKmnlhgE4CVzukw

{
  "userId": "1",
  "brand": "BMW",
  "model": "X5",
  "year": 2015,
  "vehicleClass": "SUV",
  "engineType": "FCEV",
  "licensePlate": "ABC-124",
  "imgLink": 1,
  "latitude": 44.7866,
  "longitude": 20.4489,
  "price": 100,
  "availability": true
}

###
GET http://localhost:8080/vehicles
Accept: application/json

###
GET http://localhost:8080/vehicles/659328142ba56a394ce51806
Accept: application/json

###
GET http://localhost:8080/vehicles/licensePlate/ABC-123
Accept: application/json

###
DELETE http://localhost:8080/vehicles/659328142ba56a394ce51806
Accept: application/json