### Add Vehicle #1 for Owner 1
POST http://localhost:8080/vehicles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAiLCJleHAiOjE3MzU2NDYwNzUsInVzZXJJZCI6IjY1OTJhNzRjYTg0NjM3MDgxODhjNmEwMSJ9.5R4sPftZNT1PcjN8xLQ4FIQJGzimSKmnlhgE4CVzukw

{
  "userId": "FILL_USER_1",
  "brand": "BMW",
  "model": "X5",
  "year": 2015,
  "vehicleClass": "SUV",
  "engineType": "FCEV",
  "licensePlate": "3-SKS-35",
  "imgLink": 1,
  "latitude": 51.592470,
  "longitude": 4.793560,
  "price": 125,
  "availability": true
}

### Add Vehicle #2 for Owner 1
POST http://localhost:8080/vehicles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAiLCJleHAiOjE3MzU2NDYwNzUsInVzZXJJZCI6IjY1OTJhNzRjYTg0NjM3MDgxODhjNmEwMSJ9.5R4sPftZNT1PcjN8xLQ4FIQJGzimSKmnlhgE4CVzukw

{
  "userId": "FILL_USER_1",
  "brand": "Audi",
  "model": "RS6 Avant",
  "year": 2020,
  "vehicleClass": "Luxury",
  "engineType": "ICE",
  "licensePlate": "G-888-VS",
  "imgLink": 1,
  "latitude": 51.592610,
  "longitude": 4.791830,
  "price": 199,
  "availability": true
}

### Add Vehicle #3 for Owner 1
POST http://localhost:8080/vehicles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAiLCJleHAiOjE3MzU2NDYwNzUsInVzZXJJZCI6IjY1OTJhNzRjYTg0NjM3MDgxODhjNmEwMSJ9.5R4sPftZNT1PcjN8xLQ4FIQJGzimSKmnlhgE4CVzukw

{
  "userId": "FILL_USER_1",
  "brand": "Tesla",
  "model": "Roadster",
  "year": 2010,
  "vehicleClass": "Sport",
  "engineType": "BEV",
  "licensePlate": "52-KJS-9",
  "imgLink": 1,
  "latitude": 51.589241,
  "longitude": 4.786490,
  "price": 145,
  "availability": false
}

### Add Vehicle #4 for Owner 2
POST http://localhost:8080/vehicles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAiLCJleHAiOjE3MzU2NDYwNzUsInVzZXJJZCI6IjY1OTJhNzRjYTg0NjM3MDgxODhjNmEwMSJ9.5R4sPftZNT1PcjN8xLQ4FIQJGzimSKmnlhgE4CVzukw

{
  "userId": "FILL_USER_2",
  "brand": "Toyota",
  "model": "Yaris",
  "year": 2011,
  "vehicleClass": "Compact",
  "engineType": "ICE",
  "licensePlate": "YW-790-2",
  "imgLink": 1,
  "latitude": 51.583698,
  "longitude": 4.797110,
  "price": 35,
  "availability": true
}

### Add Vehicle #5 for Owner 2
POST http://localhost:8080/vehicles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAiLCJleHAiOjE3MzU2NDYwNzUsInVzZXJJZCI6IjY1OTJhNzRjYTg0NjM3MDgxODhjNmEwMSJ9.5R4sPftZNT1PcjN8xLQ4FIQJGzimSKmnlhgE4CVzukw

{
  "userId": "FILL_USER_2",
  "brand": "Honda",
  "model": "Civic",
  "year": 2020,
  "vehicleClass": "Lower Medium",
  "engineType": "ICE",
  "licensePlate": "GX-495-K",
  "imgLink": 1,
  "latitude": 51.585720,
  "longitude": 4.793230,
  "price": 48,
  "availability": true
}

### Add Vehicle #6 for Owner 2
POST http://localhost:8080/vehicles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAiLCJleHAiOjE3MzU2NDYwNzUsInVzZXJJZCI6IjY1OTJhNzRjYTg0NjM3MDgxODhjNmEwMSJ9.5R4sPftZNT1PcjN8xLQ4FIQJGzimSKmnlhgE4CVzukw

{
  "userId": "FILL_USER_2",
  "brand": "Ford",
  "model": "Focus",
  "year": 2019,
  "vehicleClass": "Upper Medium",
  "engineType": "ICE",
  "licensePlate": "JR-888-P",
  "imgLink": 1,
  "latitude": 51.58656,
  "longitude": 4.77596,
  "price": 65,
  "availability": false
}

### Add Vehicle #7 for Owner 3
POST http://localhost:8080/vehicles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAiLCJleHAiOjE3MzU2NDYwNzUsInVzZXJJZCI6IjY1OTJhNzRjYTg0NjM3MDgxODhjNmEwMSJ9.5R4sPftZNT1PcjN8xLQ4FIQJGzimSKmnlhgE4CVzukw

{
"userId": "FILL_USER_3",
"brand": "Chevrolet",
"model": "Malibu",
"year": 1980,
"vehicleClass": "Executive",
"engineType": "ICE",
"licensePlate": "GK-19-NP",
"imgLink": 1,
"latitude": 51.5794365,
"longitude": 4.810962,
"price": 75,
"availability": true
}

### Add Vehicle #8 for Owner 3
POST http://localhost:8080/vehicles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAiLCJleHAiOjE3MzU2NDYwNzUsInVzZXJJZCI6IjY1OTJhNzRjYTg0NjM3MDgxODhjNmEwMSJ9.5R4sPftZNT1PcjN8xLQ4FIQJGzimSKmnlhgE4CVzukw

{
  "userId": "FILL_USER_3",
  "brand": "Buick",
  "model": "Roadmaster",
  "year": 1955,
  "vehicleClass": "Executive",
  "engineType": "ICE",
  "licensePlate": "DH-71-47",
  "imgLink": 1,
  "latitude": 51.577640,
  "longitude": 4.787580,
  "price": 80,
  "availability": true
}

### Add Vehicle #9 for Owner 4
POST http://localhost:8080/vehicles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAiLCJleHAiOjE3MzU2NDYwNzUsInVzZXJJZCI6IjY1OTJhNzRjYTg0NjM3MDgxODhjNmEwMSJ9.5R4sPftZNT1PcjN8xLQ4FIQJGzimSKmnlhgE4CVzukw

{
  "userId": "FILL_USER_4",
  "brand": "Mazda",
  "model": "MX-5 RF",
  "year": 2012,
  "vehicleClass": "Sport",
  "engineType": "ICE",
  "licensePlate": "TR-912-J",
  "imgLink": 1,
  "latitude": 51.57947,
  "longitude": 4.752594,
  "price": 70,
  "availability": true
}

### Add Vehicle #10 for Owner 4
POST http://localhost:8080/vehicles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAiLCJleHAiOjE3MzU2NDYwNzUsInVzZXJJZCI6IjY1OTJhNzRjYTg0NjM3MDgxODhjNmEwMSJ9.5R4sPftZNT1PcjN8xLQ4FIQJGzimSKmnlhgE4CVzukw

{
  "userId": "FILL_USER_4",
  "brand": "Ford",
  "model": "F-150 Raptor",
  "year": 2023,
  "vehicleClass": "MPV",
  "engineType": "ICE",
  "licensePlate": "V-512-XD",
  "imgLink": 1,
  "latitude": 51.587839,
  "longitude": 4.755652,
  "price": 80,
  "availability": true
}

###
GET http://localhost:8080/vehicles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAiLCJleHAiOjE3MzU2NDYwNzUsInVzZXJJZCI6IjY1OTJhNzRjYTg0NjM3MDgxODhjNmEwMSJ9.5R4sPftZNT1PcjN8xLQ4FIQJGzimSKmnlhgE4CVzukw
Accept: application/json

###
GET http://localhost:8080/vehicles/6595cb02bfaca21fd3ebd906
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAiLCJleHAiOjE3MzU2NDYwNzUsInVzZXJJZCI6IjY1OTJhNzRjYTg0NjM3MDgxODhjNmEwMSJ9.5R4sPftZNT1PcjN8xLQ4FIQJGzimSKmnlhgE4CVzukw
Accept: application/json

###
GET http://localhost:8080/vehicles/licensePlate/ABC-123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAiLCJleHAiOjE3MzU2NDYwNzUsInVzZXJJZCI6IjY1OTJhNzRjYTg0NjM3MDgxODhjNmEwMSJ9.5R4sPftZNT1PcjN8xLQ4FIQJGzimSKmnlhgE4CVzukw
Accept: application/json

###
DELETE http://localhost:8080/vehicles/659da2708cf09826e920ed4c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAiLCJleHAiOjE3MzU2NDYwNzUsInVzZXJJZCI6IjY1OTJhNzRjYTg0NjM3MDgxODhjNmEwMSJ9.5R4sPftZNT1PcjN8xLQ4FIQJGzimSKmnlhgE4CVzukw
Accept: application/json