POST http://localhost:8080/rentals
Content-Type: application/json

{
  "vehicleId": "1",
  "userId": "1",
  "date": "2020-01-01",
  "price": 100.0,
  "latitude": 15.01232,
  "longitude": 12.0122,
  "status": "PENDING",
  "distanceTravelled": 100.0,
  "score": 5
}

###
GET http://localhost:8080/rentals
Accept: application/json

###
GET http://localhost:8080/rentals/6593294bfd0c2051ae84e3cd
Accept: application/json

###
GET http://localhost:8080/rentals/user/2
Accept: application/json

###
DELETE http://localhost:8080/rentals/6593514d58f59d305f2fa133
Accept: application/json